version: "3.8"

services:
  addis-mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "7018:27017"
    volumes:
      - addis-data:/data/db
  
  addis_music-app:
    depends_on:
      - addis-mongo
    build: .
    image: addis_music
    restart: unless-stopped
    ports:
      - "3007:3007"
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URI=mongodb://addis-mongo:27017/addis-db

volumes:
  addis-data:
